### ISSUE TITLE
Combs no longer process in RoC Centrifuge since Forestry 3.6.0

### ISSUE THREAD

**Issue by Haggle1996** [ReikaKalseki/Reika_Mods_Issues#116]
With minimal modset (NEI, latest Forge, RoC v6f, and Forestry 3.6.0+), Forestry combs (and Gendustry's) no longer process in the RotaryCraft centrifuge. My uneducated guess is this occurs because Forestry updated their bee APIs in 3.6.0. Obviously, the short-term fix is not to use Forestry 3.6.0, but hopefully these APIs are/will be updated in v7.

Haggle1996/RevolutionPack#36

**Comment by ReikaKalseki** [comment]
Check your logs for errors regarding mod handlers.

**Comment by Haggle1996** [comment]
I assume this is what you're looking for.
https://gist.github.com/Haggle1996/dd92bf3515dd0334ccd8

And a second error shortly afterward:
https://gist.github.com/Haggle1996/ff2e17a29d033efa6c18

**Comment by ReikaKalseki** [comment]
Yes, it is.....crap.

I can probably fix it, but finding his new class will be a pain, and it will break my server, which is using an older Forestry copy...

**Comment by Haggle1996** [comment]
If there's anything I can do to help, please let me know.

**Comment by ReikaKalseki** [comment]
Um...any ideas on how to support both versions simultaneously? :P

**Comment by Duckfan77** [comment]
Update your server?
Also, is there any way to determine the method used to control the processing based on a check of the mod version? So that the system used is the current one for forestry before the 3.6.0, and an updated one for after.

**Comment by ReikaKalseki** [comment]
We have like 4 other Forestry addons, none of which have compatible updates yet.

**Comment by Duckfan77** [comment]
That is unfortunate, I haven't taken a look at the centrifuge code, but is there any way to switch recipie handling for forestry based on an if or something triggered by forestry version without adding huge overhead or making maintenance absurdly difficult?

**Comment by ReikaKalseki** [comment]
That was my main idea. I have no good way to read mod versions, but a "check all of these, use the first that works" kind of handling usually suffices. That said, writing code like that can get _very_ ugly.

**Comment by Duckfan77** [comment]
Isn't the mod version included in the mod data? Or at the very least in the file name, although that isn't all that safe.

**Comment by ReikaKalseki** [comment]
That does not really help me, because different versions mean different things to different mods. Unless you mean something else.

**Comment by Duckfan77** [comment]
Well, you could check if the beginning of the file name for forestry is forestry_1.7.10-3.6.*, but that is easily breakable, although it likely is inside the mod itself, so you can access the version number that determines which one is in  use.

**Comment by ReikaKalseki** [comment]
Does that correspond to the release versions, though?

**Comment by Duckfan77** [comment]
The file name at least does, I don't know if the internal value corresponds yet, but I would assume it does.

Edit: Based on a quick scan of the code, it appears to. See https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/config/Version.java and https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/Forestry.java

The versioning may not correspond to release on some mods, but it appears to for forestry.

**Comment by Duckfan77** [comment]
Just checked the contents of the jar, the version number is present in the mcmod.info, if that is accessible to you. Unfortunately, I don't yet know java to the point at which I can work on modding, and as such don't know what information from other mods is accessible.

**Comment by ReikaKalseki** [comment]
Yes, that should be accessible. I can write some handing into ModList.

**Comment by Duckfan77** [comment]
Glad to be able to help.

**Comment by ReikaKalseki** [comment]
So, it turns out the only change is that "Recipe" got changed to "CentrifugeRecipe". With the new version handling, I think this should work. I am also redesigning my mod handling system to be more dynamic and backwards and forwards compatible.

**Comment by Haggle1996** [comment]
Combs are still not working in v7b

**Comment by kolatra** [comment]
V7c is coming out today. Just wait for that, and if it still is not fixed, let us know.

**Comment by ReikaKalseki** [comment]
Check your logs again, for similar errors.

**Comment by Haggle1996** [comment]
Will do as soon as I'm home from work.

**Comment by ReikaKalseki** [comment]
You have a long commute. :P

**Comment by Haggle1996** [comment]
Dealing with my own pack issues -- all these mods just updated. :) Will get
one to you here momentarily.

**Comment by Haggle1996** [comment]
https://gist.githubusercontent.com/Haggle1996/0bdba856ff2c66a638ca/raw/a19ac8b711bea5b099316fdcf7d1df47f3c43086/gistfile1.txt

EDIT: Derp. Here's the error:
[10/7/2015 18:40:36 PM] [Client thread/INFO] [FML]: DRAGONAPI: Loading handler class Reika.DragonAPI.ModInteract.ItemHandlers.ForestryHandler for mod Forestry 3.6.2.19.
[10/7/2015 18:40:36 PM] [Client thread/INFO] [FML]: DRAGONAPI: Forestry field not found! resource
[10/7/2015 18:40:36 PM] [18:40:35] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchFieldException: resource
[10/7/2015 18:40:36 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.Class.getField(Unknown Source)
[10/7/2015 18:40:36 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.ModInteract.RecipeHandlers.ForestryRecipeHelper.<init>(ForestryRecipeHelper.java:45)
[10/7/2015 18:40:36 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

**Comment by ReikaKalseki** [comment]
Fixed fully as per IRC.

**Comment by Melakion** [comment]
Still doesn't work in V7f. 

[08:06:14] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Loading handler class Reika.DragonAPI.ModInteract.ItemHandlers.ForestryHandler for mod Forestry 3.6.3.20.
[08:06:14] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Forestry field not found! input
[08:06:14] [Client thread/INFO] [STDERR/DragonAPI]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchFieldException: input
[08:06:14] [Client thread/INFO] [STDERR/DragonAPI]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at java.lang.Class.getField(Unknown Source)
[08:06:14] [Client thread/INFO] [STDERR/DragonAPI]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at Reika.DragonAPI.ModInteract.RecipeHandlers.ForestryRecipeHelper.<init>(ForestryRecipeHelper.java:46)
[08:06:14] [Client thread/INFO] [STDERR/DragonAPI]: [java.lang.Throwable$WrappedPrintStream:println:-1]:    at Reika.DragonAPI.ModInteract.RecipeHandlers.ForestryRecipeHelper.<clinit>(ForestryRecipeHelper.java:27)

**Comment by ReikaKalseki** [comment]
Derp - field visibility. Fixed.

**Comment by Zoomg** [comment]
Having the same issue, the only bee products that work in the centrifuge is the slippery comb and propolis

Getting the first 2 lines Melakion got, but nothing else I can find:
[08:06:14] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Loading handler class Reika.DragonAPI.ModInteract.ItemHandlers.ForestryHandler for mod Forestry 3.6.3.20.
[08:06:14] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Forestry field not found! input

That is with only dragonAPI V7f, rotarycraft V7f, codechickencore 1.0.6.43, Not enough items 1.0.4.107 and forestry 3.6.3.20
Also tested with forestry 3.6.3.19 and got the exact same error(except the version of course)

**Comment by Melakion** [comment]
There hasn't been another release since this was last fixed, should work in v8.

**Comment by Haggle1996** [comment]
It was my fault -- Reika asked me if I could wait a few days for the centrifuge fix, since he had been pushing out so many v7 fixes. He just didn't quantify a 'few days'. I should have demanded a v7g right then and there. :P
