### ISSUE TITLE
Null pointer exception when crafting portal rift

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#1674]
v19
https://pastebin.com/QNm4tmhb

**Comment by ReikaKalseki** [comment]
Did you reboot the map while it was crafting? This makes no sense; it has a null recipe yet was attempting to craft it.

**Comment by Turmfalke2** [comment]
No, but there are constantly lightning strikes around it and random explosions. I get the feeling that I am supposed to put on a hood and bury a bunch of skulls below the casting altar.  

Seriously though, no I didn't. I have restarted the crafting process like 20 times before the game finally crashed with a crystalnet CME, but I did not reload the map. Is it supposed to put the altar on fire and 
temporarily reverting the altar to tier 1 and cancelling the casting?

**Comment by ReikaKalseki** [comment]
> Is it supposed to put the altar on fire and
temporarily reverting the altar to tier 1 and cancelling the casting?

That sounds like the new no-adjacent-blocks check failing in an unexpected way.

**Comment by ReikaKalseki** [comment]
Fire will no longer spawn on the table.

**Comment by Turmfalke2** [comment]
@ReikaKalseki fix was not successful, the lightning still puts the blocks around the casting table on fire breaking the structure check.

![2017-11-14_16 15 26](https://user-images.githubusercontent.com/5174562/32787559-1b180568-c957-11e7-8423-028a538446c5.png)


this is with V19c

**Comment by ReikaKalseki** [comment]
I only prevented it from putting fire on *top*.

I will make fire an allowed block around the table.

**Comment by Turmfalke2** [comment]
@ReikaKalseki any chance we could get ChromatiCraft v19d with this patched? It is the first time I am about reach the chromaticraft dimension and now I can't craft the rift blocks.

**Comment by ReikaKalseki** [comment]
Does blocking the sky above the table work around the issue?

**Comment by Turmfalke2** [comment]
At least a glass roof does not.

E: Nor does a stone roof

**Comment by Turmfalke2** [comment]
OK it is downright impossible to craft the portal rift. I got pretty close to it, but in the last few seconds of the crafting progress the lightning strikes become so frequent that it is pretty much guaranteed that one of them will light an adjacent block on fire.

**Comment by Turmfalke2** [comment]
So I worked around it. Since it is possible that I am not the only one stuck trying to craft a portal rift I am providing my workaround here.

Please note that this was done by someone who strongly dislikes Java and has minimal knowledge of modding minecraft. So instead of trying and again failing to compile ChromatiCraft I instead wrote javaagent with a class transformer to dummy out the genLightning method using asm. This is running with scissors level of stupid, don't report any bugs to anyone while using this. Don't use it for anything except crafting the portal rift. Actually just don't use it at all.

https://github.com/Turmfalke2/stupidworkaround

**Comment by OvermindDL1** [comment]
> `DieMethodDie`

Lol.  ^.^

**Comment by pairak** [comment]
Any updates on a official fix on this issue or a bypass?

**Comment by ReikaKalseki** [comment]
I think this was fixed a long time ago.

**Comment by pairak** [comment]
Server I am on is running the latest version on your page (v19c) and the issue is still there. Impossible to make the portal blocks.

**Comment by ReikaKalseki** [comment]
Several people made them on my server, also using v19c.

**Comment by pairak** [comment]
thats wierd. Cause the lightning lits the ground on fire, fire blocks the structure, craft is interrupted. Figgured it hadnt been fixed since there was no updates on this thread and it was still a open issue.

**Comment by pairak** [comment]
Also, turmfalke reported the same issue occuring for him in 19c, maybe some type of local fix is needed or something?

**Comment by Folanlron** [comment]
still is a problem, in version 19c lighting strikes around the table creating fire, fire placed at NW/SW/SE/NE directions is fine, when a fire lights in N/W/S/E sections, casting table fails structure check and dies(Open  casting table while the fire is burning you will see, that the table can no longer see the temple setup.)

Video showcasing the problem https://youtu.be/IvoRGStsDT4


**Solution**
/gamerule doFireTick false 

Removes the chance for lightning to cause fire, craft your rifts then set it too true to re-enable..

**Comment by EyeDeck** [comment]
Now that I think about it, the last time I crafted the portal rift on the dev server--probably along with everyone else since this change was made--my casting structure was in a Luminous Cliffs biome. Guess what biome fire doesn't tick in?

A temporary workaround that would probably work, then, is to fire up a biome painter and turn your casting structure into Luminous Cliffs.

**Comment by ReikaKalseki** [comment]
> my casting structure was in a Luminous Cliffs biome. Guess what biome fire doesn't tick in?

Mine as well...this might be why I thought the issue to be fixed.

**Comment by TomeWyrm** [comment]
Rainbow forest also apparently works, because I crafted my rifts earlier today just fine.

Edit, fairly close to a rainbow tree as well. With a Lumen Tree directly above my altar.

**Comment by ReikaKalseki** [comment]
Fires spread in Rainbow Forests...
