### ISSUE TITLE
Making machine with crafting table option caused the game crashed

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#1993]
Crash-report is here: https://pastebin.com/hcUNFztN

I'm trying to turn the option on but then my game crashed during the post-init period when rotarycraft is trying to register shaped recipes, is there anything I forgot to do to make it run?

By the way, I've made some modification in the form of luablock, but I didn't make anything to change the rotarycraft native recipes.

**Comment by ReikaKalseki** [comment]
Does the crash happen without those custom modifications?

**Comment by Prunoideae** [comment]
Yes, the crash remained still.

**Comment by Prunoideae** [comment]
Also, I set the option "Allow Nonstandard Recipe Modifications" to true, but I never really understand what on earth did it changed...

**Comment by Garr890354839** [comment]
> Also, I set the option "Allow Nonstandard Recipe Modifications" to true, but I never really understand what on earth did it changed...

Note that this option allows you to use minetweaker to tweak recipes. The crash I have not had and I have it enabled. Install minetweaker, that should fix this problem.

**Comment by Prunoideae** [comment]
> > Also, I set the option "Allow Nonstandard Recipe Modifications" to true, but I never really understand what on earth did it changed...
> 
> Note that this option allows you to use minetweaker to tweak recipes. The crash I have not had and I have it enabled. Install minetweaker, that should fix this problem.

It's strange that I've already installed minetweaker and when I turned the option off that crash still happened... I think it's meaningless to still work on this and I'll close this issue, just stick to worktable then :(

**Comment by ReikaKalseki** [comment]
No, but this might have already been fixed.
