### ISSUE TITLE
Liquid Chroma Reserviour Crafting with Ether Berries inconsistent

### ISSUE THREAD

**Issue by BlueAgent** [ReikaKalseki/Reika_Mods_Issues#2325]
When you try to craft more than one, same, liquid chroma recipe in the reserviour with ether berry empowerment, it results in not all off the ether berries being consumed after all the crafting operations have completed. There is inconsistent doubling of the outputs.

I think this is due to ether berry saturation only being [updated once a second](https://github.com/ReikaKalseki/ChromatiCraft/blob/f99d2f725ccbfd33829bed47741d4c709efae4f0/ModInterface/ReservoirHandlers.java#L85).

Perhaps if it was updated once per tick it would craft properly.
~~Alternatively you could slow down crafting so that it does an operation per second or longer. (But since it uses `randint(20)==0` this is still up to chance...~~ The randomness would cause it to sometimes randomly fail and that's not good.

Note this change is not that huge of a performance imact (to check each tick), since there is already an [AABB done each tick](https://github.com/ReikaKalseki/ChromatiCraft/blob/f99d2f725ccbfd33829bed47741d4c709efae4f0/ModInterface/ReservoirHandlers.java#L66).

After discussion on TS, the randomness is so the player knows the berries were disolved, as well as them taking some time to dissolve (but when it does the whole 16 berries gets consumed right away. It's not like it slowly decrements the stack, this is in line with the way chroma berries work as well)
Perhaps we could just have some particles spawn when they dissolve to indicate as such?
This would be nice to have for the Chroma Berries too

**Comment by BlueAgent** [comment]
A "kinda" work around for now is throwing in many extra stacks of ether berries.

Since it's a 5% chance per tick per stack to dissolve, if you have many extra stacks (about 40 stacks of berries extra I used seemed to work great), it makes it very likely to absorb some berries before the next crafting operation.

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by BlueAgent** [comment]
The [fix](https://github.com/ReikaKalseki/ChromatiCraft/commit/3fee5f21f35f5f0b925082767e5c755ed85ba27c#diff-8504cc5c508a93167effa162b181e3c3L85-L102) has some problems.

It's currently pausing Ether Berry consumption (I think you meant to have it pause the crafting operation instead).

Although I also see an issue with that implementation, since it's a 50% chance to dissolve each tick, you could get unlucky and lose an ingot or two being multiplied potentially (will have to look into it later).

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by BlueAgent** [comment]
So a way to address that really small chance to not duplicate, but still have the ether berries be absorbed slower is:

Make the check for ether berry absorbtion happen each tick (but not a 50% chance to fail)
Use the same data that is stored for disabling crafting for 5 ticks (it stores the time of the last berry absorbtion) to also disable ether berry absorbtion for 1 tick (which would make a berry able to be absorbed every other tick).

Ether berries will still take 32 ticks (1.6 s) to be fully absorbed with this change, but it'll be consistent rather than random.

Also has the added benifit of multiple stacks of ether berries not making multiple berries absorbed as well (resulting in faster absorbsion).

**Comment by ReikaKalseki** [comment]
Done.
