### ISSUE TITLE
[ReactorCraft] Steam Boilers not heating up from Neutron Absorbers

### ISSUE THREAD

**Issue by Thorinair** [ReikaKalseki/Reika_Mods_Issues#2414]
I am using the newest version of all the mods (v25c). I have the setup like on the pic below:
![image](https://user-images.githubusercontent.com/7534126/78906220-5c86e100-7a7f-11ea-9147-4b7fe5ea9e85.png)

The neutrons produced by the Fusion Reactor are nicely hitting the Neutron Absorbers and the absorbers are heating up and cooling down as expected. The temperatures are fluctuating between around 50C and 300C.
![image](https://user-images.githubusercontent.com/7534126/78906535-c606ef80-7a7f-11ea-8755-00fc848f5fd3.png)

However, the Steam Boilers are not changing in temperature at all. It is almost as if they transfer the cooling to the Absorers, but Absorbers don't transfer the heat to the Boilers. The boilers are constantly 21C during day (falling down to like 17 during night).
![image](https://user-images.githubusercontent.com/7534126/78906666-ef278000-7a7f-11ea-9606-8830c4aed208.png)

They also don't seem to be consuming any water, and there is no steam generated either.

Compared to this, a regular Fission Reactor setup works completely fine, and Fuel Rods are correctly transferring the heat to the Boilers.

Am I doing something wrong? Did something change? The setup on the first screenshot worked fine on the previous version of the mods that I used (v22d). If this is indeed a bug, I would assume is is related to the new heat capacity changes recently introduced. My construction of the Fusion Reactor is now put on hold, hopefully there is some sort of a fix. :)

EDIT: I can just fill up a Boiler with water and disconnect the water source as it isn't using any water anyway to keep the Absorbers cool.

EDIT2: I can even do this, and the temperatures seem to be stable at around 300C. Very wonky.
![image](https://user-images.githubusercontent.com/7534126/78907739-60b3fe00-7a81-11ea-898a-9cfbabe08c83.png)

**Comment by MalTeeez** [comment]
I encountered the same problem, the absorbers seem to be cooling down but no vaporization action is following

**Comment by Retovath** [comment]
Can confirm, Just finished my fusion build to find Fusion heat-sinking non-functional.

**Comment by ReikaKalseki** [comment]
Fixed.

![https://i.imgur.com/mH3b4hW.png](https://i.imgur.com/mH3b4hW.png)

**Comment by KassIsLegend** [comment]
im still having this issue, and he just calls it a duplicate and pretty much puts a massive middle finger in my face, boilers are not responding to temprature at all what so ever even if the neutron absorbers are at 600c

**Comment by Thorinair** [comment]
Check the date when the issue was fixed, and the date when the last downloadable update of the mod was out. The mod isn’t gonna magically absorb all the fixes. Wait for the update to come out. I know that it is frustrating, but you will have to wait just like all of us.

**Comment by KassIsLegend** [comment]
> Check the date when the issue was fixed, and the date when the last downloadable update of the mod was out. The mod isn’t gonna magically absorb all the fixes. Wait for the update to come out. I know that it is frustrating, but you will have to wait just like all of us.

true true

**Comment by KassIsLegend** [comment]
how often do updates happen, if anyone knows

**Comment by ReikaKalseki** [comment]
Using past updates as reference, major versions - which the next update is - come anywhere from a couple weeks to eight months. I *can* say that this will be on the shorter end.

**Comment by KassIsLegend** [comment]
gotcha, thank you

**Comment by KassIsLegend** [comment]
what steam level is the high pressure turbine supposed to start at...my lines are up to 250...and nothing
