### ISSUE TITLE
[Rotarycraft] Bedrock shaft freshly crafted on crafting table does not stack with bedrock shaft that has been placed in the world.

### ISSUE THREAD

**Issue by tiny-maple** [ReikaKalseki/Reika_Mods_Issues#2548]
![2020-06-01_20 53 45](https://user-images.githubusercontent.com/62176592/83411333-9b676080-a44a-11ea-8c5c-d311c0be5712.png)
![2020-06-01_20 53 35](https://user-images.githubusercontent.com/62176592/83411336-9c988d80-a44a-11ea-8bbb-6b8c652afef0.png)
Looking at the NBT tag between a crafted bedrock shaft and one that placed in the world.
Placed in world then picked up again
1 tag: bedrock
Freshly crafted is missing the bedrock tag.
No tag.

**Comment by ReikaKalseki** [comment]
This is related to #2546.

**Comment by ReikaKalseki** [comment]
This should be fixed.

**Comment by lee321987** [comment]
I'm still seeing this issue.
It might help you to know that I was unable to craft a Clutch using the "redstone dust and Steel Shaft" recipe using a freshly crafted Steel Shaft, but once I placed and picked-up the shaft then the recipe worked.

**Comment by ReikaKalseki** [comment]
Recipes do not check NBT on inputs, so I am left to think that original item was invalid somehow.
