### ISSUE TITLE
Neutron absorbers not transferring heat

### ISSUE THREAD

**Issue by rogerwim** [ReikaKalseki/Reika_Mods_Issues#2745]
My absorbers get up to 400C but boilers always stuck at 30(am using fusion reactors and 28A of both rotary and reactor craft, have electricraft installed), I have seen that there was a fix, but I am still having it, am on a superflat world, no other mods

**Comment by rogerwim** [comment]
![image](https://user-images.githubusercontent.com/33426007/108073424-503cbe80-7068-11eb-9d34-91186414e575.jpeg)![image](https://user-images.githubusercontent.com/33426007/108073444-559a0900-7068-11eb-81f8-2d84ebb544d9.jpeg)

**Comment by DanHCraft** [comment]
I have the same problem. Same Version as yours. Reactor is running, the neutron absorbers are heated between 40C in the middle and in the corners and arround 600C between the cool ones. But the Steam Boilers heating up to 41C and then dropping down to 25C after a while and the same again.

**Comment by DanHCraft** [comment]
I also want to mention that the issue is server and client side and we also do not have dynamic lights installed, so it has nothing to do with Issue #2718.

**Comment by ReikaKalseki** [comment]
I just tested and it works fine:

![https://i.imgur.com/broWpg8.png](https://i.imgur.com/broWpg8.png)

**Comment by rogerwim** [comment]
That's very odd, what version are you using?

**Comment by ReikaKalseki** [comment]
That is my dev environment, which is by definition as updated as it is possible to be...

**Comment by rogerwim** [comment]
Yup, saw eclipse, am a bit of a java programmer myself, then it could be that this was already fixed and not yet released

**Comment by rogerwim** [comment]
Oh, it has indeed been fixed, closing this

**Comment by gameskip** [comment]
Im still having this problem on version 30c after a long process building the fusion reactor, i got to the neutron absorbers and noticed that the steam boilers never went above 45C at most
![2021-10-28_21 40 36](https://user-images.githubusercontent.com/93346414/139316115-85e50a91-01d4-49c4-9e36-568ea817eea2.png)
![2021-10-28_21 40 39](https://user-images.githubusercontent.com/93346414/139316138-9753c1ad-ebc4-4504-814f-a175e931b138.png)
..
