### ISSUE TITLE
[Rotarycraft v31b] Gearboxes lose power when cold but cannot be heated

### ISSUE THREAD

**Issue by tprussak** [ReikaKalseki/Reika_Mods_Issues#3137]
Gearboxes lose power when at very low temperatures, which I believe is intended though I cannot find documentation of it. However, I cannot seem to find a way to warm the gearboxes up. I have tried fire, lava, and a friction heater to no effect. This makes the progression in very cold biomes very difficult.

**Comment by ReikaKalseki** [comment]
Fixed in v32.

**Comment by tprussak** [comment]
As of V32C, gearboxes still do not seem to accept external heating. Testing on the latest version of Dragon Realm as of 7/10/23, having a fire or lava directly underneath a gearbox does not change its temperature.

**Comment by ReikaKalseki** [comment]
It is working for me, but maybe that is v33. ![](https://i.imgur.com/rrNGk3k.png)
