### ISSUE TITLE
[Rotarycraft v31b] Fuel Converter is not affected by increased input speed.

### ISSUE THREAD

**Issue by Falgar** [ReikaKalseki/Reika_Mods_Issues#3195]
I powered the fuel enhancer with both a microturbine @ 2Mrad/s and an AC engine @ 131krad/s. Both took ~63 seconds to deplete the 5000mB input tank, which is expected if it is consuming 4mB/tick. To go along with that consumption rate, it was producing 1mB/tick of Jet Fuel.
However, according to line 199 in TileEntityFuelConverter.java, there should be a speed boost (int boost = 1+ReikaMathLibrary.logbase2(omega/MINSPEED)/2 ) dependent on the input speed. As best I can tell, this boost is always calculated as 1, meaning input speed doesn't matter.

**Comment by ReikaKalseki** [comment]
It is working fine for me. Either it got fixed by the rewrites in v32 - test again and say so if it did so I can add it to the changelog - or your tests were faulty.

I doubt v32 changed it since you referenced the code that still works.

**Comment by Falgar** [comment]
I just made a new test world and retested with v31b and the issue was still present. I updated to v32a and it has been fixed. A microturbine @2Mrad/s now consumes the input tank in ~14s rather than the 63s previously.

**Comment by ReikaKalseki** [comment]
Alright, added to the changelog.
