### ISSUE TITLE
Server running 1.7.10 crashes on DragonAPI

### ISSUE THREAD

**Issue by Benton1234** [ReikaKalseki/Reika_Mods_Issues#375]
My friends and I were making a custom modpack for ourselves and ran across this issue as the server tried to start: http://pastebin.com/0JGZUEW6

We posted this first on Reddit and got a reply not too long ago stating this:

"DragonAPI is trying to ASMing a non existing method. Just report it to Reika on his issue tracker or remove DragonAPI."

This is our mod list as well: http://imgur.com/a/p1Y98

Any help on this issue would be greatly appreciated!

**Comment by ljfa-ag** [comment]
Are any of these mods doing anything to fire? Like making it not destroy blocks or anything?

**Comment by Benton1234** [comment]
I don't believe so but how does that affect the server not starting? Also, to clarify when me and my friends run this client-side it's perfect just a heavy pack at this point.

And to run the server I am using Kcauldron Forge version 1448

**Comment by ljfa-ag** [comment]
Ah I see, KCauldron apparently does make changes to BlockFire: https://gitlab.prok.pw/KCauldron/KCauldron/blob/master/patches/net/minecraft/block/BlockFire.java.patch
Seems like the same problem has already been reported to KCauldron here: https://gitlab.prok.pw/KCauldron/KCauldron/issues/99

It should be already fixed in the current version of KCauldron.

**Comment by Benton1234** [comment]
Oh dang! Ok, I really appreciate the help but while your still here I need a question answered.

I wanted to update to the latest version of Kcauldron on Forge 1448 but when I do NEI stops working? Like just the part of NEI that gives you things like Creative+, the Saves on the right side, and things like Utility mode, Cheat mode, etc.

Any help appreciated!

**Comment by ljfa-ag** [comment]
Hm, maybe it is somehow deactivated, or NEI is incompatible with this version? Sorry, I have no clue.
That's the problem with things like Cauldron, they do unexpexcted things and can break mods this way.

**Comment by ReikaKalseki** [comment]
Also, I seem to remember this being fixed by Cauldron _six months ago_.

**Comment by Benton1234** [comment]
I read that around too but, I tried the latest version of Kcauldron using Forge 1448 and still the same error. Then I tried the Latest version of Kcauldron on Forge 1517 still the same issue.

I really can't figure out why it's being stubborn. Is there any other logs I could post that might lead to a different answer?

**Comment by Benton1234** [comment]
Ok, false alarm. Just my own stupidity. I was frustrated moving so many files around that I corrupted the libraries folder...

The only thing I have to do is run on the latest version of Forge because even the latest Kcauldron on Forge 1448 didn't fix the .Blockfire issue.

I really appreciate the help though, I knew it probably was going to be Kcauldron causing something like this to happen.

This thread can be closed as successful. If anyone needs any clarification on what I needed to do just mssg me on Steam: Benton1234.

Oh, one more thing; Reika I do appreciate you responding to my issue directly. I was actually kind of surprised haha. Either way I love your mods, keep up the awesome work!

**Comment by webbster64** [comment]
got the same problem, so looks like i have to remove all of ReikaKalseki's mods considering im going choose thermos over DragonAPI RotaryCraft ReactorCraft ElectriCraft GeoStrata, i want to give my players a stable and fun server running at 20-19tps over a server with 5 extra mods thats running at 5tps
