### ISSUE TITLE
DragonAPI incompatible with KCauldron

### ISSUE THREAD

**Issue by LemADEC** [ReikaKalseki/Reika_Mods_Issues#621]
With only KCauldron and DragonAPI, the server crashes at boot
[19:08:13 ERROR]: Encountered an unexpected exception
java.lang.VerifyError: Bad local variable type

Issue is reproduced with
 DragonAPI 1.7.10 V10d.jar + KCauldron-1.7.10-1614.175.jar (known stable)
and
 DragonAPI 1.7.10 V10d.jar + KCauldron-1.7.10-1614.188.jar (latest)

Deleting the config folder and rebooting doesn't help.

```
---- Minecraft Crash Report ----
// Sorry :(

Time: 2/10/16 7:01 PM
Description: Exception in server tick loop

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/world/WorldServer.func_147456_g()V @884: iload
  Reason:
    Type 'net/minecraft/world/chunk/storage/ExtendedBlockStorage' (current frame, locals[16]) is not assignable to integer
  Current Frame:
    bci: @884
    flags: { }
    locals: { 'net/minecraft/world/WorldServer', integer, integer, 'gnu/trove/iterator/TLongShortIterator', long, long_2nd, integer, integer, integer, integer, 'net/minecraft/world/chunk/Chunk', top, integer, integer, top, '[Lnet/minecraft/world/chunk/storage/ExtendedBlockStorage;', 'net/minecraft/world/chunk/storage/ExtendedBlockStorage', integer, integer, integer, integer, integer, 'net/minecraft/block/Block' }
    stack: { 'net/minecraft/world/WorldServer' }
  Bytecode:
    0x0000000: 2ab7 0272 033c 033d 2ab4 0276 b602 7b4e
    0x0000010: 2db9 027e 0100 9903 912d b902 8101 002d
    0x0000020: b902 8401 0037 0416 04b8 0288 3606 1604
    0x0000030: b802 8b36 072a 1506 1507 b602 8e99 0014
    0x0000040: 2ab4 0290 b402 9615 0615 07b6 029b 9900
    0x0000050: 212a b402 9ebb 02a0 5915 0615 07b7 02a3
    0x0000060: b902 a902 0057 2db9 02ab 0100 a7ff a415
    0x0000070: 0610 1068 3608 1507 1010 6836 092a b401
    0x0000080: 5413 02ad b601 5a2a 1506 1507 b602 b13a
    0x0000090: 0a2a 1508 1509 190a b602 b52a b401 5413
    0x00000a0: 02b7 b601 9319 0a03 b602 bc2a b401 5413
    0x00000b0: 02bd b601 932a b401 0e19 0ab6 02c1 9900
    0x00000c0: 782a b402 1a13 02c2 b602 c89a 006b 2ab6
    0x00000d0: 02cb 9900 642a b602 ce99 005d 2a2a b402
    0x00000e0: d106 6813 02d2 60b5 02d1 2ab4 02d1 057a
    0x00000f0: 360b 1508 150b 100f 7e60 360c 1509 150b
    0x0000100: 1008 7a10 0f7e 6036 0d2a 150c 150d b602
    0x0000110: d636 0e2a 150c 150e 150d b602 da99 0019
    0x0000120: 2abb 02dc 592a 150c 8715 0e87 150d 87b7
    0x0000130: 02df b602 e357 2ab4 0154 1302 e5b6 0193
    0x0000140: 2ab4 010e 190a b602 e899 016d 2ab4 021a
    0x0000150: 1010 b602 c89a 0161 2a2a b402 d106 6813
    0x0000160: 02d2 60b5 02d1 2ab4 02d1 057a 360b 150b
    0x0000170: 100f 7e36 0c15 0b10 087a 100f 7e36 0d2a
    0x0000180: 150c 1508 6015 0d15 0960 b602 d636 0e2a
    0x0000190: 150c 1508 6015 0e04 6415 0d15 0960 b602
    0x00001a0: eb99 005e 2ab6 0108 150c 1508 6015 0e04
    0x00001b0: 6415 0d15 0960 b602 efb9 02f5 0100 3a0f
    0x00001c0: 190f b202 fbb8 0301 b903 0702 0057 bb03
    0x00001d0: 0959 190f b903 0d01 0019 0fb7 0310 3a10
    0x00001e0: 2ab6 0242 b602 4819 10b9 024e 0200 1910
    0x00001f0: b603 119a 000c 190f 04b9 0314 0200 572a
    0x0000200: b602 cb99 0070 2a15 0c15 0860 150e 150d
    0x0000210: 1509 6004 b603 1899 005c 2ab6 0108 150c
    0x0000220: 1508 6015 0e15 0d15 0960 b602 efb9 02f5
    0x0000230: 0100 3a0f 190f b203 1bb8 0301 b903 0702
    0x0000240: 0057 bb03 0959 190f b903 0d01 0019 0fb7
    0x0000250: 0310 3a10 2ab6 0242 b602 4819 10b9 024e
    0x0000260: 0200 1910 b603 119a 000c 190f 04b9 0314
    0x0000270: 0200 572a b602 cb99 003f 2a15 0c15 0860
    0x0000280: 150d 1509 60b6 031f 3a0f 190f b603 2299
    0x0000290: 0027 2a15 0c15 0860 150e 0464 150d 1509
    0x00002a0: 60b6 0326 2a15 0c15 0860 150e 0464 150d
    0x00002b0: 1509 60b6 032a 2ab4 0154 1301 b1b6 0193
    0x00002c0: 190a b603 2e3a 0f19 0fbe 360c 0336 0d15
    0x00002d0: 0d15 0ca2 00ca 190f 150d 323a 1019 10c6
    0x00002e0: 00b8 1910 b603 3599 00b0 0336 1115 1106
    0x00002f0: a200 a72a 2ab4 02d1 0668 1302 d260 b502
    0x0000300: d12a b402 d105 7a36 1215 1210 0f7e 3613
    0x0000310: 1512 1008 7a10 0f7e 3614 1512 1010 7a10
    0x0000320: 0f7e 3615 8402 0119 1015 1315 1515 14b6
    0x0000330: 0338 3a16 1916 b603 3b99 0058 8401 012a
    0x0000340: 2db9 033f 0100 04a2 000a 2ab4 0343 a700
    0x0000350: 0613 0344 b503 4719 162a 1513 1508 6015
    0x0000360: 1519 10b6 034a 6015 1415 0960 2ab4 021a
    0x0000370: b603 4e2a 1510 1505 6015 1219 0db6 034a
    0x0000380: 6015 1115 0660 1913 b203 54b4 0357 b803
    0x0000390: 5d84 1101 a7ff 5984 0d01 a7ff 352a b401
    0x00003a0: 54b6 01f1 a7fc 6c2a b603 61b4 0364 9900
    0x00003b0: 132a b402 76b6 0367 2ab4 029e b903 6801
    0x00003c0: 00b1                                   
  Stackmap Table:
    append_frame(@16,Integer,Integer,Object[#637])
    append_frame(@81,Long,Integer,Integer)
    same_frame(@111)
    append_frame(@310,Integer,Integer,Object[#697])
    full_frame(@511,{Object[#2],Integer,Integer,Object[#637],Long,Integer,Integer,Integer,Integer,Object[#697],Integer,Integer,Integer,Integer},{})
    same_frame_extended(@627)
    full_frame(@694,{Object[#2],Integer,Integer,Object[#637],Long,Integer,Integer,Integer,Integer,Object[#697]},{})
    full_frame(@719,{Object[#2],Integer,Integer,Object[#637],Long,Integer,Integer,Integer,Integer,Object[#697],Top,Integer,Integer,Top,Object[#816]},{})
    append_frame(@749,Object[#818],Integer)
    full_frame(@849,{Object[#2],Integer,Integer,Object[#637],Long,Integer,Integer,Integer,Integer,Object[#697],Top,Integer,Integer,Top,Object[#816],Object[#818],Integer,Integer,Integer,Integer,Integer,Object[#765]},{Object[#2]})
    full_frame(@852,{Object[#2],Integer,Integer,Object[#637],Long,Integer,Integer,Integer,Integer,Object[#697],Top,Integer,Integer,Top,Object[#816],Object[#818],Integer,Integer,Integer,Integer,Integer,Object[#765]},{Object[#2],Float})
    full_frame(@913,{Object[#2],Integer,Integer,Object[#637],Long,Integer,Integer,Integer,Integer,Object[#697],Top,Integer,Integer,Top,Object[#816],Object[#818],Integer},{})
    chop_frame(@919,2)
    same_frame(@925)
    full_frame(@935,{Object[#2],Integer,Integer},{})
    same_frame(@961)

    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.7.10
    KCauldron Version: pw.prok:KCauldron:1.7.10-1614.175
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_65, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1712270016 bytes (1632 MB) / 2040201216 bytes (1945 MB) up to 4080271360 bytes (3891 MB)
    JVM Flags: 20 total; -Xms2G -Xmx4G -XX:PermSize=256m -XX:MaxPermSize=256m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:+UseParNewGC -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xnoclassgc
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAA FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.175.jar) 
    UCHIJAA Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.175.jar) 
    UCHIJAA kimagine{0.2} [KImagine] (minecraft.jar) 
    UCHIJAA <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
    UCHIJAA DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V10d.jar) 
    Profiler Position: N/A (disabled)
    Player Count: 0 / 5; []
    Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by LemADEC** [comment]
Issue is not reproduced with DragonAPI 1.7.10 V9b.jar

**Comment by Duckfan77** [comment]
Known issue, this is on the end of KCauldron. Any Bukkit versions are unsupported, as discussed [here](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/541).

**Comment by coolsquid** [comment]
#541

**Comment by LemADEC** [comment]
Do we have a ticket open on KCauldron side for this?

**Comment by ReikaKalseki** [comment]
Also, this is already fixed in v11.

**Comment by LemADEC** [comment]
Thanks!

**Comment by Crowfooted** [comment]
I'm still having this issue with DragonAPI and Chromaticraft V11a - [here's the crash report](http://pastebin.com/jXg0zKe9). I am using Thermos instead of KCauldron, since it's updated to the most recent (and recommended) version of Forge for 1.7.10 (version 1558), which KCauldron seems not to be.

**Comment by ReikaKalseki** [comment]
> I am using Thermos instead of KCauldron

Then this fix will not work.

**Comment by Crowfooted** [comment]
Just tested with KCauldron and you are correct. But I'm interested to know what it is about Thermos that causes this crash when KCauldron doesn't. Presumably, you know some specifics?

**Comment by zemerick** [comment]
I'm not familiar with Thermos, but I would imagine it's the same reason KCauldron often doesn't work when Forge does. They changed something so it no longer behaves as expected.

**Comment by LemADEC** [comment]
Both sides are doing low level code changes to the same class of the original game. Issue will resurface periodically until a common API is defined.

**Comment by ReikaKalseki** [comment]
And seeing as the Bukkit/Cauldron/MCPC/KCauldron/Spigot/Thermos/NewNameToAvoidCopyrightTakedownHere builds keep changing names, versions, structures. owners, and implementations, there is nothing I can do.

**Comment by TomeWyrm** [comment]
Bukkit/Cauldron/MCPC/KCauldron/Thermos/IllegalSoftwareYouReallyAllOughtToQuitUsingBecauseItBreaksAllTheThings-GetAForgeDeveloperToMakeTheStuffYouNeedBecauseForgeIsBetterThanBukkit

Fixed that for you Reika :-p

**Comment by ReikaKalseki** [comment]
They are not mutually exclusive.

**Comment by TomeWyrm** [comment]
> Issue will resurface periodically until a common API is defined.

It's called Forge.

Actually I just thought of a better way to phrase the thing Reika. 

Anything Bukkit could do Forge can do too. (Just maybe not with current mods.)

**Comment by ReikaKalseki** [comment]
> Anything Bukkit could do Forge can do too. (Just maybe not with current mods.)

They would need a couple additional patches, but that is easily done, or the mod needing them can ASM them in.

**Comment by webbster64** [comment]
got the same problem, so looks like i have to remove all of ReikaKalseki's mods considering im going choose thermos over DragonAPI RotaryCraft ReactorCraft ElectriCraft GeoStrata, i want to give my players a stable and fun server running at 20-19tps over a server with 5 extra mods thats running at 5tps
