### ISSUE TITLE
Crash with extractor when inserting ores Rotarycraft V13a

### ISSUE THREAD

**Issue by Phalanxguard** [ReikaKalseki/Reika_Mods_Issues#859]
Running FTB Infinity Evolved with custom mods:
Rotarycraft
Reactorcraft
Electricraft
Dragon API
Voltz Engine
ICBM

Possibly cross mod interaction with Voltz Engine V 10b160 caused the error. Disabled AOBD to check it wasn't causing the issue before reporting. Server crashes when inserting any ore into extractor.

Crash log:
http://pastebin.com/T7SktmVu

**Comment by ghost** [comment]
Try updating to v13b.

**Comment by ReikaKalseki** [comment]
You have an ore mapped to two different conflicting OreDict names. And you are using an old version.

**Comment by Phalanxguard** [comment]
As far as I can see the latest version of Rotarycraft on Curse is V13a, only Reactorcraft, Electricraft and Dragon API have V13b versions. Thanks for the information about the OreDict names.

**Comment by Phalanxguard** [comment]
Do you want to reopen this issue Reika? Darkguardsman suggested you'd be fixing it on your end. If or when you patch it, if you post here I'll be more than happy to test it out for you.

**Comment by ReikaKalseki** [comment]
It was fixed in v14.

**Comment by Phalanxguard** [comment]
I tried it with V14b this morning and it still crashed. Same conditions as the last time.

Pastebin report is here: [http://pastebin.com/NkkTkm7c](http://pastebin.com/NkkTkm7c)

**Comment by ReikaKalseki** [comment]
Fixed.

**Comment by Phalanxguard** [comment]
Cheers Reika, much appreciated.
